trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:  # Add jobs section
      - job: BuildJob  # Job name
        steps:  # Correctly indented steps under the job
          - task: Maven@4
            displayName: 'Build the Package'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              goals: 'clean package'
      - job: PublishArtifact
        steps:    
          - task: PublishBuildArtifacts@1
            displayName: 'Publish The Artifact'
            inputs:
              PathtoPublish: 'webapp/target/webapp.war'  # Path to the specific artifact
              ArtifactName: 'webapp'              # Name for the published artifact
              publishLocation: 'Container'
