trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPackageJob
        steps:
          - task: Maven@4
            displayName: 'Build the Package'
            inputs:
              mavenPomFile: 'webapp/pom.xml'  # Ensure this points to the correct POM file
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              goals: 'clean package'

          - script: |
              ls -l webapp/target  # List contents of the target directory for verification
            displayName: 'List contents of target directory'
          
          - task: CopyFiles@2
            displayName: "Copy Files to Staging Path"
            inputs:
              SourceFolder: "webapp/target/webapp.war"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            displayName: 'Publish The Artifact'
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"  # Correct path to the WAR file
              ArtifactName: 'webapp'
              publishLocation: 'Container'
